FROM php:7.2-apache

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN apt-get update && \
    apt-get install -y libxml2-dev \
	vim \
	mc \
	zlib1g-dev \
	libpng-dev \
	libfreetype6-dev


